### ISSUE TITLE
Support boolean

### ISSUE THREAD

**Issue by leeuwe** [MarketSquare/localization#3]
https://github.com/robotframework/robotframework/issues/4400 would allow for boolean operator to be translated. Add these to the script

**Comment by pekkaklarck** [comment]
I believe we'll add these to the `Language` class

```python
true_strings = set()
false_strings = set()
```

and then the `En` class will get

```python
true_strings =  {'TRUE', 'YES', 'ON', '1'}
false_strings = {'FALSE', 'NO', 'OFF', '0', ''}
```

Not sure should generic `'1'`, `'0'` and `''` be in the base class but that doesn't really affect translations.
